const mongoose=require('mongoose');
mongoose.connect('mongodb://localhost:27017/Mobile');
const PlatfromSchema=new mongoose.Schema(
    {
        platname:
        {
            type:String,
            require:true,
            unique:true
        },
        name:
        {
            type:String,
            require:true
        },
        Bio:
        {
            type:String,
            require:true
        },
        followers:
        {
            type:Number,
        },
        following:
        {
            type:Number,
        },
        post:
        {
            type:Number
        },
        Reached:
        {
            type:Number,
        },
        engaged:
        {
            type:Number,
        },
        Content:
        {
            type:Number,
        },
        Ads:
        {
            type:Number,
        },
        promotions:
        {
            type:Number,
        },
        stories:
        {
            type:Number
        },
        follows:
        {
            type:Number,
        },
        posts:
        {
            type:Number,
        },
        saves:
        {
            type:Number,
        },
        comments:
        {
            type:Number,
        },
        shares:
        {
            type:Number,
        
    }
}
);
const platfrom=mongoose.model('platfrom',PlatfromSchema);
module.exports=platfrom;